### ISSUE TITLE
Improve interaction system

### ISSUE THREAD

**Issue by netfusion** [TaktiCool/ArmaAtWar#165]
To simulate BI actions we need more possibilities in our interaction system:
- [ ] Provide a variable distance dependent on action target (see _getInRadius_ in _CfgVehicles_)
- [ ] Provide an array to multiply actions (_GetInTurret_ action is there once per turret)
- [ ] Increase condition performance by executing code dependent only on __target_ once when action gets added (optional, hard)
- [ ] Allow passing an _icon_ as argument
- [ ] Allow passing an dynamic _priority_ as argument (based on distance for example)
- [x] Allow passing an _hideOnUse_ as argument

This is needed to fake some BI actions.
The vehicle restriction implementation could use _GetInX_/_MoveToX_ actions with custom conditions.

**Comment by jokoho48** [comment]
i think a CanInteract System would be good for the Interaction menu. where we can define general Condition. Ref ACE3 CanInternact.

**Comment by jokoho48** [comment]
we need to check what badguy allready build in https://github.com/drakelinglabs/projectrealityarma3/pull/299

**Comment by netfusion** [comment]
Radius and Distance are two parameters for the same use. We should use only one.
