### ISSUE TITLE
Squad Leader can't promote Squad Members

### ISSUE THREAD

**Issue by filipbasara** [TaktiCool/ArmaAtWar#245]
### ArmA3 Version:

Launcher version: 1.5.136470
Game version: 1.60.136470
Branch: main / beta branch not specified
### PRA3 Version:

0.6
### Mods:

none
### Description:

As Squad Leader, pressing the promote button after selecting a Squad Member does not do anything.
### Steps to reproduce:

Press on Squad Member, Promote, No effect
### Where did the issue occur?

Official Playtest

**Comment by TomNedry** [comment]
QA started!

**Comment by pwilkutowski** [comment]
Rep produced on:

Launcher version: 1.5.136470
Game version: 1.60.136470
Branch: Current Master


Prerequisites:
2 players on the server 
 - Player A 
 - Player B


- Player A creates a Squad
- Player B Joins created Squad
- Player A promotes player B to squad leader

Issue occurs 
 -  player B cannot be promoted
 - player A squad menu glitches out (glitched buttons)

**Comment by Ribbonius** [comment]
Seems to work on the 24/7 servers.
Got promoted and was able to kick or promote squadmembers after I got promoted.

**Comment by Hoegnison** [comment]
I also couldnt reproduce anymore
