### ISSUE TITLE
Leaving and rejoining a Squad as Squad Leader will keep Squad Leader Role

### ISSUE THREAD

**Issue by filipbasara** [TaktiCool/ArmaAtWar#246]
### ArmA3 Version:

Launcher version: 1.5.136470
Game version: 1.60.136470
Branch: main / beta branch not specified
### PRA3 Version:

0.6
### Mods:

none
### Description:

Leaving and rejoining a Squad as Squad Leader will keep Squad Leader Role
### Steps to reproduce:

Leave squad and rejoin as SL, You'll stay Squad Lead

**Comment by filipbasara** [comment]
probably referred to #245

**Comment by litrax** [comment]
+ Create Squad
+ Choose Squad Leader Role
+ Leave Squad
+ Join Squad
+ The chosen Role is automatically Squad Leader (instead of nothing or rifleman)

**Comment by Hoegnison** [comment]
should be fixed
