### ISSUE TITLE
Empty vehicles should be visible on the map

### ISSUE THREAD

**Issue by Hoegnison** [TaktiCool/ArmaAtWar#357]

**Comment by simon84** [comment]
Empty vehicles of own side should be gray now.

**Comment by litrax** [comment]
Will test it today or tomorrow...

**Comment by TomNedry** [comment]
Tested in mission: AAW_VDev, 0.16.0.1912
Empty vehicles are not visible on the map on start. They got a green icon during use and are again not visible after using them (empty again).

**Comment by simon84** [comment]
You are on the wrong branch. Please review it on master branch.

**Comment by TomNedry** [comment]
Tested and is working
