### ISSUE TITLE
Kit selection Restriction dont work

### ISSUE THREAD

**Issue by jokoho48** [TaktiCool/ArmaAtWar#367]
if you have a Limited kit you can select every Limited Kit even if all Limite Classes are allready gone

**Comment by jokoho48** [comment]
this need to be discussed later how we want to handle this. move to RespawnUI Rewrite

**Comment by Hoegnison** [comment]
We are reworking kits etc. so I guess we gonna close this right?

**Comment by jokoho48** [comment]
yes
