### ISSUE TITLE
Unconscious Player changes stance to prone while beeing dragged

### ISSUE THREAD

**Issue by litrax** [TaktiCool/ArmaAtWar#372]
### ArmA3 Version:
- 1.64.138732
### PRA3 Version:
- 0.12
### Mods:
- No Mods
### Description:
- Unconscious Player changes stance to prone while beeing dragged.
### Steps to reproduce:
- Player A gets shot unconsious. Player B drags unconsious player. If the unconscious player A presses a key to change stance ( in our case Strg + C or C for Combat-Pace ) the dragged and unconcious player gets prone during the drag action. Meaning he turns round during beeing dragged.
### Where did the issue occur?
- Testserver

**Comment by jokoho48** [comment]
issue is from old revive system #closed
