### ISSUE TITLE
When incapacitated players should not be able to move their heads

### ISSUE THREAD

**Issue by filipbasara** [TaktiCool/ArmaAtWar#384]
### Description:
- As suggested by a play tester

**Comment by jokoho48** [comment]
to be true, i am not sure if we can do something against it. as far i can remeber we wound need to change animation config for that.

**Comment by TomNedry** [comment]
I assume that the request means that an incapacitated player shouldn't be able to give any intel to his team. An solution would be to do e.g. a blur filter on the players view.

**Comment by Hoegnison** [comment]
I do not see this request coming up very frequently tbh. Furthermore we are running low on resources atm so I reject that request for now. If it comes up again we can reiterate.
