### ISSUE TITLE
PRA3 information section on Arma3 "menu screen" is cutted off

### ISSUE THREAD

**Issue by TomNedry** [TaktiCool/ArmaAtWar#394]
### ArmA3 Version:
+ 1.64.138732
### PRA3 Version:
+ 011441Anov16

### Mods:
+ None

### Description:
+ On the Arma 3 "Main menu screen" (that after pressing ESC in a mission), the section for the PRA3 information and "Report issue" link in the right bottom corner is cutted off to the right [(see screenshot)](https://www.airpressuretendency.net/pra3_qa_3jdurhtdx997sk/20161101142534_1.jpg) so the mission version is cutted of too.

### Where did the issue occur?
+ PRA3 Test Server

**Comment by Hoegnison** [comment]
fixed or still present?
