### ISSUE TITLE
Solo tanking discussion

### ISSUE THREAD

**Issue by netfusion** [TaktiCool/ArmaAtWar#397]
@TomNedry:
> In PR:BF2 you can operate the assets with a single person. As you probably know there is a "switch timer" which creates an artificial delay, so you need about 30 seconds (see PR:BF2 Manual for v1.3) to switch between positions in tanks and similar vehicles and a shorter time period to switch such positions in "light assets" (e.g. Humvee). This is to prevent "alone wolf" behaviour...
> 
> Although it's a game design descision, i agree with Montie that from a players point of view it's not logical that a gunner or a commander position can't be manned by any player with crew-kit without a driver being in the vehicle. To prevent "alone wolfs" please see the paragraph above...

**Comment by pwilkutowski** [comment]
I would suggest retaining similar timer behavior. 
Depending on complexity, suggested solutions are:

**Solution 1**
 - User gets in, 
 - User switches position
 - Position switch timer is enabled with cool down time (Tiger off, sights off, etc..)

**Solution 2**
 - User gets in, 
 - Position switch timer is enabled, blocking position switch other than \Get out\ Disembark\

**Solution 3**
 - User gets in
 - User needs to get out, and get in to change position
 (may be problematic for some assets ...i guess)

Solution 3 seems to speak to me personally as the animations take time, also a freeze timer can be introduced to simulate 'seating in / spool up time'


**In case of solutions 1/2 possible problem:**

- User gets in, 
- position switch timer is enabled
- User gets out and gets in directly to new position

Not sure if ArmA can retain information that user was IN a position and if we want to retain that information, and the animations take a while so this should be minimal problem

**Comment by Randall172** [comment]
Instead why don't you disallow switching positions inside the vehicle.

to switch positions would require you to exit the vehicle and approach from the correct angle to get back in.

exceptions would be for commander/gunner, but the driver seat would in effect be "isolated".

**Comment by Bluedrake42** [comment]
I want to make sure that everyone understands this functionality is already in the game. I'm not sure if everyone understands that and is just discussing the system anyways? However it is not possible to have a gunner without a driver. That is already in the modification.

Currently players require a crewman role to access a tank. The gunner position requires a driver. The commander position also requires a driver (however we're looking at removing the commander position requirements.)

**Comment by pwilkutowski** [comment]
'...Currently players require a crewman role to access a tank. The gunner position requires a driver. The commander position also requires a driver (however we're looking at removing the commander position requirements.)...'

The switching question still remains valid - if a driver is in tank should a commander be allowed to instantly switch to gunner position and other way around ?
