### ISSUE TITLE
Repair Station in HQ?

### ISSUE THREAD

**Issue by Hoegnison** [TaktiCool/ArmaAtWar#415]
Could we add a repair station in base?

**Comment by Hoegnison** [comment]
We need a big static object in the base that repais, refuels and rearms friendly vehicles.

**Comment by netfusion** [comment]
Supply system is finished
We need to place it into the missions
Example configuration is here:
https://github.com/TaktiCool/ArmaAtWar/blob/master/mission/AAW_vDev.Stratis/cfgEntities.hpp#L53

**Comment by netfusion** [comment]
-[ ] AAW_OP_TakeKavala_Inf.Altis
-[ ] AAW_operation_spartan_shield_NATO_AAF_AAS.Altis
-[ ] AAW_operation_spartan_shield_NATO_AAF_AAS_Infantry.Altis
-[ ] AAW_playtest_NATO_AAF.Stratis
-[ ] AAW_playtest_NATO_CSAT.Stratis
-[x] AAW_vDev.Stratis
