### ISSUE TITLE
Implement dead dead

### ISSUE THREAD

**Issue by Hoegnison** [TaktiCool/ArmaAtWar#431]
If a player gets revived by a non medic his blood lvl does not get a reset. His blood regenerates in a slow rate though. 
This will prevent medic/revive trains and adds more dynamic into defensive situations which are the main component of aas.

**Comment by pwilkutowski** [comment]
0.14.0.1800

Seems it isn't working:

 - Geting shot in the head by non medic
 - Revived by non medic
 - Shot agian in the head

I can be revived b non medic

**Comment by Hoegnison** [comment]
@simon84 maybe this needs some input from you but in my understnading it is possible that if you get revived fast enough you can get shot more than 2 times. Is that correct?
Can you test this again in order of *Bescherung 2.0*

**Comment by simon84** [comment]
Yes hoegi, that is right. The current implementation is different from the first draft of hoegi. When you are unconscious, you are loosing blood. When you are revived, the blood restores slowly. So, if you are shot quickly after your first time, the unconscious time is lower and you die faster. You can estimate your blood level with the Color saturation. The medic can restore your blood by healing.

**Comment by Hoegnison** [comment]
Needs some testing again I guess

**Comment by pwilkutowski** [comment]
Tested by:
 - Tom 
 - Pchelka 

It seems that the unconscious timer is shorter after each revive for both medic and other classes.

Example:
 - 2nd revive by medic had ~27s time until dead 
 - 3rd revive by medic had ~10s count downs for dead - dead

If I recall this properly medic should always reset the count down clock to max allowed time
