### ISSUE TITLE
Discuss how to indicate if a player is in your squad, fireteam or side

### ISSUE THREAD

**Issue by filipbasara** [TaktiCool/ArmaAtWar#440]

**Comment by Hoegnison** [comment]
Nametags
Map
Ui Elements

**Comment by pwilkutowski** [comment]
Eventual Glyphs maybe ? 
Hollow ASCII CODE 254 - fire team
ASCII CODE 254 - Squad
ASCII CODE 79 - Side

**Comment by Hoegnison** [comment]
Visual language allread got an update
