### ISSUE TITLE
Heavy asset & vehicle logistics/airlifting

### ISSUE THREAD

**Issue by Bluedrake42** [TaktiCool/ArmaAtWar#441]
DRK= Bluedrake42: Potential heavy asset airlifting solution: as brainstormed and outlined by @NetFusion @[DEV] Mitsu and @=DRK= Bluedrake42 

► Create new action for vehicle commander "Mothball"
- Mothballing ejects all crewmen from the vehicle, locks the vehicle, depleats all fuel, depleats all ammo
- Only "Mothballed" vehicles can be airlifted

► Create new logistics objects spawnable at main base
- One time use "Vehicle Repair" crate
- One time use "Vehicle Rearm" crate
- One time use "Vehicle Repair" crate

![image](https://cloud.githubusercontent.com/assets/7584028/20238610/69c59eca-a8bd-11e6-9409-5c98767372dc.png)

★ Purpose
- Heavy assets (or any assets potentially) can be airlifted to anywhere on the map, but only while "Mothballed." This decreases their combat effectiveness, and means vehicles that are transported greater distances from main base... will take more time to make combat ready (transporting the rearm and refuel supplies take multiple trips, compounded with distance travelled from main base.) 

- This will allow for a balanced logistical solution to transporting heavy assets, while making their transportation vastly negate their combat effectiveness... so proper placement of vehicles should be considered, and multiple "re-deployments" are both costly and time-consuming.

- This also creates a repair/rearm/refuel solution that is universal, but also uniquely balanced for heavy asset airlifting. These logistical assets can also be pre-emptively deployed to forward outposts, or other parts of ther map, similar to how traditional ammo boxes (and other supplies) are pre-emptively supplied to the front line.(edited)

★ Additional
- This also makes vehicle in vehicle loading (when applicable) much more valuable/balanced, since it won't require vehicles to be "Mothballed." However "VIV" capable vehicles require much more space (such as runways) to be effective... making traditional sling loading still a viable alternative. So the choice for players will be:

1. Slingload vehicle, but suffer extended combat readiness deployment time.
2. Cargo load vehicle, but suffer limited capacity (most VIV capable vehicles can't load tanks) and also limited deployment flexibility (most VIV capable vehicles can't land outside of runways/landing zones)

**Comment by Hoegnison** [comment]
I see that as a task for 2017. Moved to Backlog for now. But sill open for comments and general thoughts. Personally I like the idea of having that type of fix wing deployment. But we should not mix it. So if we decide to do this type of deployment there should no other way to deploy a fix wing. At least in our vanilla version of pra3 :) Otherwise it will end up confusing people.

**Comment by Hoegnison** [comment]
Discussion is outdated
