### ISSUE TITLE
Fixed Wing Employment

### ISSUE THREAD

**Issue by Bluedrake42** [TaktiCool/ArmaAtWar#455]
Here is a potential solution for fixed wing employment for Project Reality: ArmA III.
Originally pitched by @NetFusion and modified by @=DRK= Bluedrake42 

► Create a terminal at main base, which allows pilots to deploy into off-map aircraft when available.
- When deployed, an aircraft spawns in-flight off-map (with pilot inside)
- Whenever the aircraft moves to an off-map area, the pilot has an option to "Depart" which rearms/repairs/refuels the aircraft, but requires half the vehicle's respawn time to do so.

★ Purpose
- This will allow fixed wing aircraft to be deployed on any map, regardless of base position or airfield availability. However for maps that do have airfields available... these airfields can be used to decrease the redeployment time of fixed wing aircraft, by allowing them to land and be refueled/repaired/rearmed by friendly forces on the ground. However any attempt to land potentially puts the aircraft at risk of an enemy ground attack.

**Comment by Hoegnison** [comment]
depricated
