### ISSUE TITLE
Implement Mortar UI

### ISSUE THREAD

**Issue by Hoegnison** [TaktiCool/ArmaAtWar#460]
Implement Mortar Ui according do Mockups

**Comment by simon84** [comment]
Is available in mortar branch.

Explanation:

- bottom left: mortar calculator
- first line: input fields (R00000 E+0000, Range and Elevation (Height difference))
- line C1 - C2 solution for each charge configuration (00.00/00 Angle of Elevation/Time over Target)

- bottom right: current mortar configuration (number of charges and angle of elevation)

- bottom center: rangefinder, press LockTarget ("T" in Default Layout) to measure a range

**Comment by litrax** [comment]
Unclear was the input of a negative height difference.
Please clarify...

**Comment by litrax** [comment]
Change input of height difference. 
- Minus is bound to "chat"
- Minus (NumPad) is bound to "zoom out"
