### ISSUE TITLE
find all Missing Icons and find New Icons for version after 1.66

### ISSUE THREAD

**Issue by jokoho48** [TaktiCool/ArmaAtWar#463]

**Comment by TomNedry** [comment]
PRA is using this PAA-files

a3\Data_f\cfgFactionClasses_BLU_ca.paa
a3\Data_f\cfgFactionClasses_IND_ca.paa
a3\Data_f\cfgFactionClasses_OPF_ca.paa
a3\ui_f\data\IGUI\Cfg\Actions\gear_ca.paa
a3\ui_f\data\igui\rscingameui\rscdisplayvoicechat\microphone_ca.paa
a3\ui_f\data\map\Markers\Military\box_ca.paa
a3\ui_f\data\map\Markers\Military\dot_ca.paa
a3\ui_f\data\Map\Markers\NATO\b_installation.paa
a3\ui_f\data\Map\Markers\NATO\n_installation.paa
a3\ui_f\data\Map\Markers\NATO\o_installation.paa
a3\ui_f\data\Map\Markers\NATO\u_installation.paa
a3\ui_f\data\Map\Markers\System\dummy_ca.paa
ui\media\badClientFrames_ca.paa
ui\media\badServerFrames_ca.paa
ui\media\fob_ca.paa
ui\media\loadingscreen_co.paa
ui\media\notification_gradient_ca.paa
ui\media\PRA3Logo_ca.paa
ui\media\rally_ca.paa
\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa
\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa
\a3\ui_f\data\IGUI\Cfg\Actions\clear_empty_ca.paa
\a3\ui_f\data\igui\cfg\holdactions\drawicon_incapacitated_ca.paa
\A3\Ui_f\data\IGUI\Cfg\HoldActions\holdAction_forceRespawn_ca.paa
\A3\Ui_f\data\IGUI\Cfg\HoldActions\holdAction_revive_ca.paa
\A3\Ui_f\data\IGUI\Cfg\HoldActions\progress\progress_0_ca.paa
\A3\Ui_f\data\IGUI\Cfg\Revive\overlayIcons\u100_ca.paa
\A3\ui_f\data\igui\cfg\simpleTasks\types\defend_ca.paa
\A3\ui_f\data\map\mapcontrol\bunker_ca.paa
\A3\ui_f\data\map\mapcontrol\bush_ca.paa
\A3\ui_f\data\map\markers\nato\b_inf.paa
\A3\ui_f\data\map\vehicleicons\iconMan_ca.paa


**The only missing one is:**
\a3\ui_f\data\igui\cfg\holdactions\drawicon_incapacitated_ca.paa

I have no glue how it looked like...!?

**Comment by simon84** [comment]
Should be fixed now.

**Comment by pwilkutowski** [comment]
The revive icon is ok both 2d/3d
We may still be missing 2d icon (map) for wounded, when 3d icon is active - 2d is not shown
