### ISSUE TITLE
Reload Tank in Base emptys all shells

### ISSUE THREAD

**Issue by litrax** [TaktiCool/ArmaAtWar#506]
### ArmA3 Version:
+ 1.66.139586

### AAW Version:
+ 0.16.0.1912

### Mods:
+ No Mods

### Description:
+ If you have a full LMG but empty 120mm cannon, then choosing the option "Supply M2A1 Slammer at Vehicle Ammo [NATO]" sets the LMG shells to zero and don't supplies your cannon.
So your tank is all empty and useless now.

### Steps to reproduce:
+ Get in M2A1 Slammmer as gunner.
Shoot all cannon rounds. 
Leave the LMG untouched.
Drive to the static vehicle ammo box in the nato base.
Get out of the tank.
Choose option "Supply M2A1 Slammer at Vehicle Ammo [NATO]" in mouse wheel menu.
Get in the tank as gunner.
All shells (cannon and LMG) are emtpy now.
The option to resupply the tank never shows up again.
Your tank becomes useless.

### Where did the issue occur?
+ Testserver

**Comment by TomNedry** [comment]
The vehicle re-ammo function still sets the ammo of each used magazine to zero, instead of refilling it.

**Comment by netfusion** [comment]
Tested steps to reproduce and everything worked fine

**Comment by litrax** [comment]
No Crew Kit available!? Can't get in tank...

**Comment by litrax** [comment]
Appreciate the fast help to test it.
Everything works fine now with reloading tanks.
