### ISSUE TITLE
Respawn of Vehicle Driver lets vehicle dissapear on map

### ISSUE THREAD

**Issue by litrax** [TaktiCool/ArmaAtWar#507]
### ArmA3 Version:
+ 1.66.139586

### AAW Version:
+ 0.16.0.1912

### Mods:
+ No Mods

### Description:
+ If a vehicle is maned by e.g. a driver and displayed colored on the map and the driver respawns then the vehicle is not visible on the map any more, until a new driver gets in to that vehicle.

### Steps to reproduce:
+ Get in a vehicle
Respawn
Then the vehicle is no longer visible on the map:

![20170215_232615](http://i.imgur.com/lxyPgbUh.jpg)

If you get in that vehivle as driver again, the vehicle is visible as colored vehicle again.
If you then get out, the vehicle is shown as grey vehicle again:

![20170215_232815](http://i.imgur.com/C9FSnAOh.jpg)

Maybe related to #501 

### Where did the issue occur?
+ Testserver

**Comment by simon84** [comment]
should be fixed on master

**Comment by litrax** [comment]
IS fixed on master
