### ISSUE TITLE
Text of created rally point cropped in the message box

### ISSUE THREAD

**Issue by litrax** [TaktiCool/ArmaAtWar#508]
### ArmA3 Version:
+ 1.66.139586

### AAW Version:
+ 0.16.0.1912

### Mods:
+ No Mods

### Description:
+ The text of the message of the created rally point is cropped at the end, so that the player could not read the place where the rally point is placed

### Steps to reproduce:
+ Get to Camp Tempest
Create a rally point
Following message is cropped:

![20170215_233715](http://i.imgur.com/No0SQqFl.jpg)

The player doesn't know near wich camp a rally point is created.

### Where did the issue occur?
+ Testserver

**Comment by jokoho48** [comment]
invalide because of rework of the UI. the current Notification system will be replaced in some versions.
