### ISSUE TITLE
Stuck in rally point tent

### ISSUE THREAD

**Issue by adgamer01** [TaktiCool/ArmaAtWar#512]
### Description:
+ It did not happen very often and all it really does is get you stuck in the rally point tent. You can just easily vault out of it but it is a little annoying. I don't think this is at all that bad of a bug but it would be nice if it were fixed.

### Steps to reproduce:
+ Spawn in on tent
+ Gets stuck in tent

### Where did the issue occur?
+ This issue occurred on the playtest server

**Comment by jokoho48** [comment]
should be fixed by @simon84. if it happens again we will open a new issue
