### ISSUE TITLE
Message of Rally Point of other Squad poped up

### ISSUE THREAD

**Issue by litrax** [TaktiCool/ArmaAtWar#513]
### Description:

A message of a new Rally Point poped up. 
But the Squad Leader hasn't set one.
Definitively it was meant the Rally Point of the other Squad.
But this Rally Point is uninteresting for the  own Squad, cause you don't have the chance to spawn there.

![123](http://i.imgur.com/16nAfx9.jpg)

Shortly after this  the SL of the own Squad really placed a Rally Point. And the same message appears, but this time it's correct and usefull.

![456](http://i.imgur.com/VRPKj8D.jpg)

### Steps to reproduce:

Get in the game in Squad A. Another player must join the team and open up Squad B.
If SL Squad B places a Rally Point you get a message.
This message is useless for your Squad and should not popup...

### Where did the issue occur?

Playtest 25.02.2017

**Comment by simon84** [comment]
Already fixed in 8031b2a
