### ISSUE TITLE
FOB should not be buildable while dragged around

### ISSUE THREAD

**Issue by litrax** [TaktiCool/ArmaAtWar#521]
### AAW Version:
+ 0.16

### Mods:
+ No Mods

### Description:
+ If you drag the FOB and SL builds it, you are still (virtually) draging it and are fatigue all the time

### Steps to reproduce:
+ Drag FOB
+ SL builds FOB while it is beeing dragged
+ Draging player still is slow.

FOB should not be buildable while dragged around.

### Where did the issue occur?
Dev Build on Testserver

**Comment by jokoho48** [comment]
i currently just temp fixed this with in the drag/drop function. so that if someone build a FOB its just "drops" it. we need to invesigate why the canInteract system is not triggering here
