### ISSUE TITLE
Mouseover tooltip of vehicle broken if players respawn

### ISSUE THREAD

**Issue by litrax** [TaktiCool/ArmaAtWar#522]
### AAW Version:
+ 0.16

### Mods:
+ No Mods

### Description:
+ If a player in a vehicle respawns, the mouseover tooltip shows "Error: No unit"!

### Steps to reproduce:
+ Get in a vehicle
+ Respawn
+ Hover mouse over left vehicle.
+ The mouseover tooltop shows the already respawned player as if he still is in the vehicle
+ The name of the player in the vehicle can't be determined anymore, so the tooltip shows "Error: No unit" for every respawned player.

+ If one player in a vehicle respawns:
![20170303214814_1](https://cloud.githubusercontent.com/assets/18654669/23569115/01078602-005e-11e7-8fcf-1ffe63b761d0.jpg)

+ If two players in a vehicle respawn:
![20170303214959_1](https://cloud.githubusercontent.com/assets/18654669/23569118/057db710-005e-11e7-8d83-bde5077d3b8d.jpg)

### Where did the issue occur?
+ Testserver

**Comment by jokoho48** [comment]
0cec528a98d7db50bd0ed40d0a8d9a34b5b6ffd5 and cd199456fb801be8c815fb07789caae74541882f should have allready fixed this

**Comment by litrax** [comment]
F§$%ing Server should run on master when QA comes in testing  ;-) ;-)
