### ISSUE TITLE
Port all Modules to new settings system

### ISSUE THREAD

**Issue by jokoho48** [TaktiCool/ArmaAtWar#530]
- [ ] BaseProtection
- [x] Common
- [ ] CompassUI
- [x] FOB
- [x] Rally
- [x] Kit #475 
- [x] Logistic
- [x] RespawnUI
- [x] Revive
- [ ] Sector
- [x] Squad
- [ ] Supply
- [ ] Tickets
- [x] UnitTracker
- [ ] VehicleRespawn

**Comment by simon84** [comment]
see global config branch (#577)
