### ISSUE TITLE
Recon Squad dont have a Sniper

### ISSUE THREAD

**Issue by jokoho48** [TaktiCool/ArmaAtWar#533]

**Comment by Hoegnison** [comment]
couldnt reproduce, which mission? Was the error that the sniper kit did not have a sniper rifle or that the rec on squad didnt have a sniper kit.

**Comment by jokoho48** [comment]
i think @netfusion repored that originaly. and i think he forgot that the sniper is a Limited Kit

**Comment by Hoegnison** [comment]
We couldnt reproduce. I will close this for now.
