### ISSUE TITLE
can Switch Side Restriction dont work correctly

### ISSUE THREAD

**Issue by jokoho48** [TaktiCool/ArmaAtWar#534]
after what i noticed Switch Side Playercount Diff Restriction is not working correctly. because in the first round we had 29 vs 18

**Comment by pwilkutowski** [comment]
This will need a bit  of ppl for testing

**Comment by jokoho48** [comment]
the Side Restriction doesnt worked at all. do to a wrong used variable in fn_canSwitchSide but that is fixed with in db113035613dfacd92d727e6c61e9efd96542fec

**Comment by pwilkutowski** [comment]
Tested using current master branch

The warning massage is appearing BUT the undecided pliers that are joining server as independent team are counted as a side and are triggering the balance warning message

independent team needs to be excluded form balance player count function

Bug reopened

**Comment by jokoho48** [comment]
please do not test in dev mission. please use one of the playtest missions. the current dev mission is configured that the notification trigger at 0 player diff for testing reasons

**Comment by pwilkutowski** [comment]
Having some problems with gathering enough ppl to test this the way i need to test it 
it will drag a bit

**Comment by pwilkutowski** [comment]
Closed for now
