### ISSUE TITLE
Vehicles on Transport Heavy missions respawnen to slow.

### ISSUE THREAD

**Issue by jokoho48** [TaktiCool/ArmaAtWar#535]
on Transport Heavy mission Vehicles respawnen to slow for getting the mission flow running and may let a team that have a bugged Heli loose the round

**Comment by litrax** [comment]
I can't change to transport heavy mission. No Admin rights on Testserver. I think I had it once...!?

**Comment by litrax** [comment]
The Vehicle Respawn is O.K. as it is. I checked in mission Spartan Shield.
In the moment the helis respawn after 8 Min, Tanks after 15 mins.

There are 2 transport helis and an attack heli on each side. Should be enough.
If one transport heli bugs the team still got another one.
If the attack heli or the tank should be bugged, it's hard luck.

The fact that helis andtanks are valuable assets makes the time justified.

In comparison to Squad, which can not directly compare, but to get a feeling of respawn times of assets in general, the respawn time of the most valuable assets, the BTR and Stryker, is 8 mins. The 30mm BTR has an even longer respawn time of 15 mins!
