### ISSUE TITLE
Using SimpleObjects/Objects for GlobalNamespaces

### ISSUE THREAD

**Issue by jokoho48** [TaktiCool/ArmaAtWar#541]
currently we using Units for Global Namespaces and i think that we could switch to Objects to remove the "Logic Group" because i think that this could be faster.

we also can test if we maybe can use a SimpleObject for namespaces.

**Comment by jokoho48** [comment]
https://github.com/TaktiCool/CLib/pull/13

**Comment by jokoho48** [comment]
done and merged :D

**Comment by jokoho48** [comment]
should be in master. and if the sectors still work fine everything should work

**Comment by Montiemedia** [comment]
It works!
