### ISSUE TITLE
Add bearing to compass UI

### ISSUE THREAD

**Issue by Hoegnison** [TaktiCool/ArmaAtWar#551]
Add bearing to compass ui. For example on top of the compass you could display the bearing number

**Comment by jokoho48** [comment]
as far i remeber we allready talked/discussed about that and decided against it.

we sad that we want the user to think about the barring and not just read a number.

**Comment by filipbasara** [comment]
Suggesting to get feedback from community on this.

**Comment by Hoegnison** [comment]
we have more and more people asking for it and i do not see the point in giving the players a usefull UI elemtn but missing out that crucial feature.

**Comment by Hoegnison** [comment]
we decided that most people are liking the compass in the way as it is right now. The number of people who want it more subtile and who want more features like a bearing are relativly even. Maybe we need a survey.
