### ISSUE TITLE
Create basics tutorial

### ISSUE THREAD

**Issue by Ribbonius** [TaktiCool/ArmaAtWar#558]
Containing the following:

>
- How to join a server

- Gamemode - AAS
	- how AAS works
	- Ticket System
		(how to decrease enemy tickets, ticket bleed)

- Squads & Kit System
	- Unlocking squads
		(eg. Heli squad)
	- Createing a squad
		(communication with other squads)
	- Kit System
		(unlocking kits, kit regulation)

- Tasks as a Squadlead
	- Ralleypoints
		(requirements, propertys, enemys nearby)
	- FOBs
		(requirements, propertys)

- Logistics
	- Where to get ammunition boxes, importance of logistics

- Little features
		(draging unconcious soldiers, hold actions eg. reviving)

**Comment by Hoegnison** [comment]
This wont happen due a short time frame of ribbon, which we are going to use for PR
