### ISSUE TITLE
Welcome screen with external html element

### ISSUE THREAD

**Issue by Hoegnison** [TaktiCool/ArmaAtWar#563]

**Comment by netfusion** [comment]
Need text + design

**Comment by pwilkutowski** [comment]
Moved to QA

**Comment by pwilkutowski** [comment]
I don't have the content to display so just the screen is tested
There is one bug as mouse over focus is not placed until user execute 'click' action this meanst that following use case is broken:

 - place mouse over continue (button is highlighted)
 - Press Enter keystroke 

There is on reaction, i need to TAB in the focus for keyboard action to work
Its anal i know but be glad im not testing this for accessibility for blind users XD

**Comment by pwilkutowski** [comment]
Ok not a bug this is vanilla behavior

**Comment by litrax** [comment]
It's o.k. now.
