### ISSUE TITLE
Base Protection can be bypassed while reloading

### ISSUE THREAD

**Issue by filipbasara** [TaktiCool/ArmaAtWar#565]
### ArmA3 Version:
+ latest stable

### AAW Version:
+ 0.18.0.2056

### Description:
+ Reloading a weapon and the immediately holding down LMB allows the player to fire inside the base until they run out of ammo

### Steps to reproduce:
+ Spawn, stay in base, press R to reload, immediately press and hold LMB

### Where did the issue occur?
+ Dedicated

**Comment by jokoho48** [comment]
should be fixed in master

**Comment by pwilkutowski** [comment]
Seems to be fixed -  i cannot reload and shoot using this trick
Closing as fixed
