### ISSUE TITLE
Add timer before match is starting (e.g 90 seconds)

### ISSUE THREAD

**Issue by filipbasara** [TaktiCool/ArmaAtWar#566]
Add a timer that prevents spawning of all players. This allows players to spawn at the same time and give them some time for preperation and to form squads. Timer should be a minimum of 90 seconds.

**Comment by Hoegnison** [comment]
I really like the idea. It is used in PR and Squad for preparation and planning. SLs have the chance to communicate with each other and their squad. Will make the start of each round more relaxed. 

Pls make the time configurable with a serversided default :)

**Comment by litrax** [comment]
Wanted to test, but it made me wait ~ 225 **HOURS** to spawn.

Till then in 9 days  ....   ;)

**Comment by simon84** [comment]
ok, should be fixed now. Please test in master. Dev mission has only a 5 sec counter. so should be testet on different mission.

**Comment by Hoegnison** [comment]
Done and tested
