### ISSUE TITLE
Steam connect doesn´t work via Website

### ISSUE THREAD

**Issue by Montiemedia** [TaktiCool/ArmaAtWar#568]
On the Website the Links, example "steam://connect/213.239.202.133:2313", doesn`t work. 
https://developer.valvesoftware.com/wiki/Steam_browser_protocol

Steam does not open!

**Comment by jokoho48** [comment]
it works on my side

**Comment by netfusion** [comment]
Should be fixed. Thanks for the info.
(Refresh cache to verify)

**Comment by pwilkutowski** [comment]
Moved to QA

**Comment by litrax** [comment]
It generaly works.

Problem 1: The first time one connects it needs about 40 sec from clicking the button to this screen:

![hc_048](https://cloud.githubusercontent.com/assets/18654669/25458260/882ae016-2ad9-11e7-9df8-a469cf451e83.jpg)

Problem 2: Depending on the handler, that users have in Firefox, the link will eventually not work.
But that's not in our hands. One has to choose this option:

![hc_049](https://cloud.githubusercontent.com/assets/18654669/25458322/c6ad31a4-2ad9-11e7-918e-abb16e244c25.jpg)

In general it takes a little time till the Arma Launcher shows up, but that is a steam issue.
Other connect links I tried e.g. from Discord to a Squad Server took also about 20 secs...

So it's working for now.
Closed. As issue #562  is also closed by me then...
