### ISSUE TITLE
Respawn Point Locked Time is scalar NaN

### ISSUE THREAD

**Issue by jokoho48** [TaktiCool/ArmaAtWar#570]
![Image](https://puu.sh/vl4Ob/15daef103d.png)

maybe a serverTime issue or maybe a deployment point data issue and maybe ref to https://github.com/TaktiCool/ArmaAtWar/issues/556 need QA @TaktiCool/qa 
that is the video i saw it in
https://www.youtube.com/watch?v=7IaaXdvJ6fw&feature=youtu.be

**Comment by netfusion** [comment]
![20170415235237_1](https://cloud.githubusercontent.com/assets/11633525/25067039/011fb406-2238-11e7-8848-e43e4448d0b0.jpg)
Could reproduce it.
Error is probably use of unknown variables here:
https://github.com/TaktiCool/ArmaAtWar/blob/master/serverAddons/AAW/addons/AAW_Server/RespawnUI/fn_clientInitDeployment.sqf#L111

**Comment by simon84** [comment]
tested and fixed
