### ISSUE TITLE
PBO Project dont allow to build missions

### ISSUE THREAD

**Issue by jokoho48** [TaktiCool/ArmaAtWar#581]
`In File \AAWMissions\AAW_playtest_NATO_AAF.Stratis\ui\common\baseclasses.hpp: Line 267 access= anything is a reserved keyword`

**Comment by netfusion** [comment]
probably not our fault because `PBO Manager` and `armake` both work fine

**Comment by jokoho48** [comment]
confirm fix with https://github.com/TaktiCool/ArmaAtWar-Missions/commit/eeb009fba2d9d6949aedf929a6221bbec8544576
