### ISSUE TITLE
Kit must be clicked twice to see the actual loadout.

### ISSUE THREAD

**Issue by litrax** [TaktiCool/ArmaAtWar#591]
### ArmA3 Version:
+ 1.68

### AAW Version:
+ 0.19

### Mods:
+ No Mods

### Description:
+ You must click two times to see which loadout you are getting with the chosen kit.

### Steps to reproduce:
+ Get in Spawn-Screen
+ Select a kit
+ The correct loadout is not shown
+ Click the kit again
+ The correct loadout for the kit is shown

### Where did the issue occur?
+ Testserver ( Masterbranch)

**Comment by simon84** [comment]
should be fixed

**Comment by litrax** [comment]
Reopened this issue cause it was there again on the current version of the Armaworld Server.

**Comment by simon84** [comment]
Yes, the issue is fixed on the current master along with some ui improvements (you see now all kits, number of kits and kit limit)
