### ISSUE TITLE
Ingame voice chat not being received by team members

### ISSUE THREAD

**Issue by voshond** [TaktiCool/ArmaAtWar#594]
### ArmA3 Version:
arma3client_x64_performance_168_141598_v19

https://forums.bistudio.com/forums/topic/160288-arma-3-stable-server-168-performance-binary-feedback/?do=findComment&comment=3185266

### AAW Version:
02.20.0.2202

### Mods:
No Mods installed
### Description:
As usual, i use the default keybind (CAPSLOCK) for ingame voice chat. I made sure i was in the group channel and pressed and holded the Push to talk button to communicate with my team. Tho i can hear my Team's coms it seems my voice cannot be heard by my team. I was connected in discord at the time and there my team was able to hear me.

### Steps to reproduce:
1) Press and Hold Capslock
2) Speak
3) Wait for response

### Where did the issue occur?
On the Playtest Server from the playtest on the 13th May of 2017
IP: 213.239.202.133
Port: 2332

### RPT log file:
+ No Crashfile was created.

**Comment by Hoegnison** [comment]
Please keep an eye on this issue during the upcoming iteration. It might have something to do with 64 bit but we can not reproduce it atm. It might be on BIs end but I want to be sure. So try to investigate during our weekly playsessions but do not spend to many resoruce on it besides your other tasks. 

After the iterations is over we gonna decide how we are going to proceede.

**Comment by Hoegnison** [comment]
Issue closed, we have to monitor this issue, though
