### ISSUE TITLE
FOB- Name not visible in spawn screen

### ISSUE THREAD

**Issue by litrax** [TaktiCool/ArmaAtWar#599]
### ArmA3 Version:
+ 1.70 (stable/rc/dev)

### AAW Version:
+ v A20.0.2022 

### Mods:
+ No Mods

### Description:
+ FOB- Name not visible in spawn screen

### Steps to reproduce:
+ If a FOB is still locked (that is the case for a few minutes after it's just build up) the name of the FOB is blinking in the spawn screen. If you, in this state, click on the FOB symbol of this locked FOB **on the map**, than the name of the FOB cannot be read in the deployment section on the right side of the spawn screen. This is propably because the text has the same color as the selection bar!?

![hc_053](https://cloud.githubusercontent.com/assets/18654669/26609607/5e6ad45a-45a2-11e7-90b4-9c8c95bccce6.jpg)

### Where did the issue occur?
+ AAW Testserver

**Comment by jokoho48** [comment]
> This is propably because the text has the same color as the selection bar!?

yes

**Comment by jokoho48** [comment]
will be not existing with new Respawn Screen
