### ISSUE TITLE
Concept for increasing spawn time

### ISSUE THREAD

**Issue by Hoegnison** [TaktiCool/ArmaAtWar#605]

**Comment by simon84** [comment]
Currently implemented in 4a53e80:
`respawnTime = max(configuredRespawnTime - timeBeingUnconsciousness, 0);`
with `0 < timeBeingUnconsciousness < maxUnconsciosnessTime`
currently configured with:
```
configuredRespawnTime = 40 s // AAW >> CfgRespawn >> respawnCountdown
maxUnconsciosnessTime = 180 s // AAW >> CfgRevive>> unconsciousDuration
```
