### ISSUE TITLE
Vehicle Icon have Wrong Color

### ISSUE THREAD

**Issue by jokoho48** [TaktiCool/ArmaAtWar#616]
Normal:
![1Group](https://puu.sh/wnHXP/fcee512837.png)
Abnormal:
![Abnormal](https://cdn.discordapp.com/attachments/173543220582547456/326069175619682306/unknown.png)

my current theory is that when 2 groups are in 1 vehicle the 1 Icon gets rendered 2x 1. Blue and then Green over it.

**Comment by simon84** [comment]
Maybe fixed withj: https://github.com/TaktiCool/CLib/commit/776bf1cfb53df049f6954d4485aa437129aa6a66 ???

**Comment by jokoho48** [comment]
good point closing for now
