### ISSUE TITLE
Provide easy way to change the player via script

### ISSUE THREAD

**Issue by netfusion** [TaktiCool/ArmaAtWar#629]
If you change the player via script it takes one frame until CLib triggers the `playerChanged` event. 
To prevent errors you may have to trigger it manually right after you changed the player (CLib_fnc_triggerEvent).

Unfortunately, CLib does not recognize the change and will trigger the `playerChanged` event again which leads to two events for only one player change.

My recommendation is to add a function to CLib to change the player which handles all variables (inside CLib).
As always feel free to write comments if u have alternative ideas.

**Comment by jokoho48** [comment]
https://github.com/TaktiCool/CLib/commit/0bd8ebdb1e01d4fa56bb8f5d40928623b6a7c6e2
https://github.com/TaktiCool/ArmaAtWar/commit/de37ca00db7ffbf6c5872f5016bb2068b5a89575
